export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS =  "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE"

export const GET_GOODS = 'GET_GOODS';

export const SUCCESS = 'SUCESS';
export const ERROR = 'ERROR';
export const CLEAR = 'DESTROY';

export const CHANGE_MENU_KEY = "CHANGE_MENU_KEY";