export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const REGISTER_SUCCESS =  "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE"

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS= 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const SUCCESS = 'SUCESS';
export const ERROR = 'ERROR';
export const CLEAR = 'DESTROY';

export const CHANGE_MENU_KEY = "CHANGE_MENU_KEY";

export const GET_CART_REQUEST = 'GET_CART_REQUEST';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const SET_CART_REQUEST = 'SET_CART_REQUEST';
export const SET_CART_SUCCESS = 'SET_CART_SUCCESS';
export const SET_CART_FAILURE = 'SET_CART_FAILURE';

export const GET_MISSION_REQUEST = 'GET_MISSION_REQUEST';
export const GET_MISSION_SUCCESS = 'GET_MISSION_SUCCESS';
export const GET_MISSION_FAILURE = 'GET_MISSION_FAILURE';

export const SET_USERCOUPON_REQUEST = 'SET_USERCOUPON_REQUEST';
export const SET_USERCOUPON_SUCCESS = 'SET_USERCOUPON_SUCCESS';
export const SET_USERCOUPON_FAILURE = 'SET_USERCOUPON_FAILURE';

export const GET_USERCOUPON_REQUEST = 'GET_USERCOUPON_REQUEST';
export const GET_USERCOUPON_SUCCESS = 'GET_USERCOUPON_SUCCESS';
export const GET_USERCOUPON_FAILURE = 'GET_USERCOUPON_FAILURE';